ansible_server_user: ENC[AES256_GCM,data:j6pij5nw,iv:kh0W9L5PkUP7Z6l17Kl4HLNcevnOelhP8+jvFn2WNtU=,tag:hGXGX6l40Lybm4EH9caXnQ==,type:str]
ansible_server_password: ENC[AES256_GCM,data:fZQvEGXhlg==,iv:kJ+Hnf4jhWDU4gbN2IEQ1P7AxR+OMtUHOZ3rjUqtb5A=,tag:u2P76fGYAKIvV7XAY3rCXQ==,type:str]
ansible_server_become: ENC[AES256_GCM,data:jsytLhXP9Q==,iv:BgHFzkgnOBuxYHs8OneCr7OlXH8P1s7TADSgsLMdfTQ=,tag:X/5sSibT+86/T6Wz3lJlIw==,type:str]
sops:
    age:
        - recipient: age1suhranahglufhj8xag53upej8qva28k973psdjf96xsqnduakfvs3y620p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQVBRZnVxNGdKeC9LKzRW
            MTlHNzFtYjZyNWY3S3pFaXVOUlhkNlRPd1NJCnd6K2tWRFBmWFI1TUg1MjYvQ1l6
            dndmZWVLSFU0R2RvTlJWVTZIMXArUDQKLS0tIEpIaG0wWWVFNGRqQWgvRjd5czcw
            elNTMGVPU1J5WDJ3MlRNWVl3ZGp1eDAKmhN4A834tOdGHXClE5bCYqj67G4clypZ
            /VF8eZe1O/GcCQvnwSc1CvcbtNDtmAISuT9vo32dAd43G4kW4jBb+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T02:32:34Z"
    mac: ENC[AES256_GCM,data:Q1xKDO6Gx8ijzWvf8sLARWLbZPBOsBRk4klJGwU1cihZ/RcLPJTNGWxIHgF7hXJu4IHk5gx7ilzDiws86WvnDLdDxjsBbZC590y9W2qlk3msuvpFT6D1MRpXf8KiICrmyAUN+yeXCEXwnQ1KHrDNpN9DwN56gyY53ZjWSwuZQLI=,iv:Ag5yczY3LEJJbTCw5M2eNj9h0eHs7KL7kJ/flKzxE9k=,tag:oG8Q4xuuc316cMJmxK3SHg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
