ansible_user: ENC[AES256_GCM,data:wS0Oy3NiqA==,iv:feeNWxCT18ZO7bjbChCg2VEC01DBkUoyPLRUdi+A+Xg=,tag:O0O1kHWz6we0HUkFVq3nkQ==,type:str]
ansible_password: ENC[AES256_GCM,data:yOjVc2GSluLZlukoIg==,iv:33jR+PMhO0pr+ynlRFI+w9BdtWJDoebMToYA829IGJQ=,tag:eNqd1u/W/mCigWhIyjkIDg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:D6QzOCZlNgF0gsB78A==,iv:GnRVJYKx+46No8rGBJRR99tivwPIuvS/ETDajymZwDg=,tag:26TA3LjTTFL7yvRUp5KyEg==,type:str]
sops:
    age:
        - recipient: age1suhranahglufhj8xag53upej8qva28k973psdjf96xsqnduakfvs3y620p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNEJIT3N2UlJSdzNKSkZ3
            eXg5czFnL09jV3dPNzJxbzRyM29UaU8xdkRjCnJqWnppdXRaWFV3OW90N3pzRVBF
            S3ozejNlaDkzWWtDaGw5b1REdHY2ZDAKLS0tIHRaU3hmcE5HenlrdlpzcnJlTkk4
            SkRTblpvZ3pISlZzcy9SRUx6WHh5akUKx9ms1LIcg9+0APnfIkEvFKdkL0XsRbfT
            o/QFfR3iSUVFb5Vrx+ebNtGv3PEwFWFSMld08JMgUPuzqRE1kWOIrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T19:01:04Z"
    mac: ENC[AES256_GCM,data:ubygZdkPs7ennRV05HLC8G6PvWGsI++s0yVDcFI8J7vxExY6kc77IlcEMSzrFdmk/43JSbRvZlrgwf+7wCsz7rKG7gvfUTazPOed44UgY7dgYjB28HtKBOZHtkCkUWeEKFpkYznW7CHSQE/y6BviS1julo74KN/GEJ3exhqF+b4=,iv:mMKiPCMNyMpJ60IH7DzaouHZxGWsqAVPHscxZmzt1mc=,tag:P60r0Sc10j/ByHNEvreN9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
